### ISSUE TITLE
 save them as PDF ?

### ISSUE THREAD

**Issue by germanvaleroelizondo** [bfh/moodle-quiz_archive#1]
Hi,

I was trying your new plugin at https://moodle.org/plugins/quiz_archive, but I could not find a way for a techer yo **easily** save a PDF of the output. 

If I use the print as PDF option in Firefox, a very large amount of the space is taken by the left hand side column with the navigation and administration blocks in the Clean theme.

Using the Boost theme, I can hide the left panel easily, but the user needs to acces the cogwheel and choose Results/Archive in order to show the Archived results for the quiz.

Maybe some additional instructions could help, but it would be ideal to add a 'Save as PDF' button (if possible).

Thanks in advance.

**Comment by lucaboesch** [comment]
Thanks for your report, German.
You are right.
In our theme, we have things like

/* Print styles */

@media print {
    #block-region-side-pre {
        display: none;
    }
}

(and similar exclusions for print)
and therefore my print as PDF gives a quite pretty output.

I'll think about something. In the meantime, adding the above to your Clean's custom CSS might help.

Best,
Luca

**Comment by lucaboesch** [comment]
Dear German
The print stylesheet has been adopted to leave out the left hand side column with the navigation and administration blocks as well as the header and the footer and all other unused stuff.
Unfortunately adding a "Save as PDF" button is not an option. PDF generation on the server side would be much too much complicated. Therefore users have to provide the export to PDF themselves, or it is completely free to them to simply send the reported quiz attempts to a printer.
Best,
Luca

**Comment by germanvaleroelizondo** [comment]
Thanks for the info Luca,
Germán
