### ISSUE TITLE
Show "There are no attempts to show" (quiz|noattemptstoshow) when no attempts are there.

### ISSUE THREAD

**Issue by lucaboesch** [bfh/moodle-quiz_archive#14]
Now when there are 
☐ Include response history table
☐ Include correct answer banner
options and the "Show report" button it is weird if an empty page reloads as soon as "Show report" is pressed when there are no quiz attempts at all.

**Comment by PhilippImhof** [comment]
Good point. I'll take care of that, if you don't mind.

**Comment by lucaboesch** [comment]
That would be lovely, yes!
I saw at https://github.com/bfh/moodle-quiz_archive/blob/941f4f1666a3c0cd5d8479012e30b38974146c40/archive_table.php#L67 this is something you might be able to reuse.
