### ISSUE TITLE
Deal with empty quiz

### ISSUE THREAD

**Issue by PhilippImhof** [bfh/moodle-quiz_archive#18]
Currently, if a quiz contains no questions, we see this:

![image](https://github.com/bfh/moodle-quiz_archive/assets/52650214/3ea6d43d-2786-46ac-a3b8-cdad5b3fbe05)

I suggest changing it and show the "no attempts to show" message, because 
* while the message is not wrong at all, accessing this report would be a strange way to go to the quiz' edit page;
* if there are no questions, there can be no attempts, so the message I suggest would also be factually correct

What do you think, @lucaboesch?

**Comment by lucaboesch** [comment]
Yes, quiz|noattemptstoshow would definitely be better, @PhilippImhof .

**Comment by lucaboesch** [comment]
Oh I get it, it is on top of the other commit!

**Comment by lucaboesch** [comment]
I just saw the other reports all use nothingfound|quiz_grading.
Could you maybe change to that one, too?
