### ISSUE TITLE
change current version in version.php to v4.3-r2

### ISSUE THREAD

**Issue by ksteitz** [bfh/moodle-quiz_archive#23]
The version.php was updated to "$plugin->version = 2023111100;" last week (also at https://moodle.org/plugins/pluginversion.php?id=30469), but the update to v4.3-r2 is missing in the release-line: 

old:
$plugin->release = 'v4.3-r1';

new:
$plugin->release = 'v4.3-r2';

**Comment by lucaboesch** [comment]
Thanks, @ksteitz !
I have to fix this and align with a v4.3-r3…
