### ISSUE TITLE
report by group user

### ISSUE THREAD

**Issue by nicola-milani** [bfh/moodle-quiz_archive#3]
Is it possible to get a report splited by group?
thanks!

**Comment by lucaboesch** [comment]
The quiz activity does not seem to restrict teacher role persons to see results from people in groups they're not member of (Group mode: Seperate groups). At least my trying out of this does result in that conclusion. In quiz activity view it says: "Attempts: 2 (1 from your groups)" and you are allowed to see both attempts and grades.

So, this is not supported I'm afraid.

Best,
Luca
