### ISSUE TITLE
Gherkin?

### ISSUE THREAD

**Issue by remcoNL** [bfh/moodle-quiz_archive#5]
As I see you've made some tests in Gherkin. This made my admin to believe he needs to install or use Gherkin next to PHP. I don't think that is true. 

Can you please confirm that Gherkin is not necessary and this plugin behaves like any other Plugin? 

That would be great, thanks.

**Comment by lucaboesch** [comment]
Yeah, you don't need Gherkin.
It's not for the end user and the Moodle running sites but to run automated tests developer side.
You see such files all over Moodle (those with the .feature suffix).
Best,
Luca
